<?php

/**
 * @file
 * Checks if your site was hacked.
 *
 * @todo: get rid of functions below in favour of OOP.
 */

/**
 * Check if there is any changes in the site repository.
 *
 * @return bool
 *   TRUE there is any change in the site repository.
 */
function is_hacked_hacked() {
  return (bool) is_hacked_get_report();
}

/**
 * Returns vcs status command output.
 *
 * @return array
 *   Array of vcs command output.
 */
function is_hacked_get_report() {
  $output = [];

  exec(is_hacked_get_vcs_command(), $output);

  return $output;
}

/**
 * Get vcs command.
 *
 * @return string
 *   VCS command to check the site repository status.
 */
function is_hacked_get_vcs_command() {
  return \Drupal::config('is_hacked.settings')->get('vcs');
}
