# Schema for the configuration files of the Is Hacked module.

is_hacked.settings:
  type: config_object
  label: 'The Is Hacked module settings'
  mapping:
    vcs:
      type: string
      label: 'VCS status command'
